from:
- toolbox/.toolbox/deps/toolbox-cicd-build/config/build.deliverables.yaml

components:
  master:
    repo: git@github.com:aroq/toolbox-docman-example.git
    root_repo: git@github.com:aroq/toolbox-docman-example.git
    hooks:
      builder:
        after_execute:
          - type: :yaml_execute
            environments: [dev, stage, preprod, prod]
            # commands:
              # - "rm -f .gitignore"
              # - "cp -f .gitignore.docroot .gitignore"
          - type: :yaml_execute
            environments: [local, dev, stage, preprod, prod]
            commands:
              - git rev-parse --short HEAD > REVISION
              # - "composer install --prefer-dist --optimize-autoloader"
              # - "if [[ -d vendor ]]; then find vendor -type d -name .git -exec rm -rf {} +; fi"
              # - "if [[ -d docroot/modules/contrib ]]; then find docroot/modules/contrib -type d -name .git -exec rm -rf {} +; fi"
              # - "if [[ -d docroot/themes/contrib ]]; then find docroot/themes/contrib -type d -name .git -exec rm -rf {} +; fi"
              # - "if [[ -d docroot/libraries ]]; then find docroot/libraries -type d -name .git -exec rm -rf {} +; fi"
