deps:
  toolbox: github.com/aroq/toolbox?ref=master
  toolbox-cicd-build: github.com/aroq/toolbox-cicd-build?ref=v0.1.1

from:
- toolbox/.toolbox/deps/toolbox/config/toolbox.settings.yaml
- toolbox/.toolbox/deps/toolbox-cicd-build/config/toolbox.settings.yaml

config:
  libraries:
    cicd:
      params:
        env:
          VARIANT_CONFIG_DIR: .
      component:
        commands:
          build:
            params:
              config_context_prefix:
              - .toolbox.build
