deps:
  toolbox: github.com/aroq/toolbox?ref=develop
  toolbox-cicd-build: github.com/aroq/toolbox-cicd-build?ref=master

from:
- toolbox/.toolbox/deps/toolbox/config/toolbox.settings.yaml
- toolbox/.toolbox/deps/toolbox-cicd-build/config/toolbox.settings.yaml

tools:
  test:
    from:
    - config.libraries
    cmd: test
  config:
    from:
    - config.libraries
    cmd: config

