deps:
  toolbox: github.com/aroq/toolbox?ref=develop
  # toolbox-cloud: github.com/aroq/toolbox-cloud?ref=master
  # infra-k8s-root: git@code.adyax.com:zebra-infra/intra-k8s-root.git?ref=master

from:
- toolbox/.toolbox/deps/toolbox/config/toolbox.settings.yaml

tools:
  test:
    from:
    - config.libraries
    cmd: test

